version: '3.1'
services:
  web:
    image: odoo:12.0
    container_name: odoo12-exercise
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - web-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./extra-addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres:13
    container_name: postgres-db-test
    ports:
      - "52314:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    restart: always
volumes:
  web-data: